version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    volumes:
      - .:/app
      - /app/node_modules  # Persist node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Optional: for hot reloading
    env_file:
      - .env